source("functions.R")
source("~/Desktop/Research/mortalityResidualsAndVaccineUptake/R/allCauseAndCirculatory.R")
source("~/Desktop/Research/mortalityResidualsAndVaccineUptake/R/vaccineUptake.R")
source("~/Desktop/Research/mortalityResidualsAndVaccineUptake/R/addingPopulation.R")
source("~/Desktop/Research/mortalityResidualsAndVaccineUptake/R/addingCovidDeath.R")
source("~/Desktop/Research/mortalityResidualsAndVaccineUptake/R/stateData.R")
source("~/Desktop/Research/mortalityResidualsAndVaccineUptake/R/testing.R")
